import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const status = JSON.parse(await readFile(path.join(root, '.env.supabase.status.json'), 'utf8'));
const apiUrl = status.API_URL;
const anonKey = status.ANON_KEY;
const serviceKey = status.SERVICE_ROLE_KEY;
const url = new URL(apiUrl);
if (!['127.0.0.1', 'localhost', '[::1]'].includes(url.hostname) || url.protocol !== 'http:') {
  throw new Error('Refusing to seed a non-local Supabase backend.');
}
if (!anonKey || !serviceKey) throw new Error('Local Supabase status did not return the required keys.');

const health = await fetch(`${apiUrl}/auth/v1/health`, { headers: { apikey: anonKey } });
if (!health.ok) throw new Error('Local Supabase Auth is not healthy.');
if (process.argv.includes('--status')) {
  console.log(`Local Captuto Supabase is healthy at ${apiUrl}.`);
  process.exit(0);
}

// Keys come from the local CLI only. Cloud .env.local is never read or changed.
await writeFile(path.join(root, '.env.supabase.local'), [
  '# Generated by scripts/dev-backend.sh. Local Docker credentials only; do not commit.',
  `NEXT_PUBLIC_SUPABASE_URL=${JSON.stringify(apiUrl)}`,
  `NEXT_PUBLIC_SUPABASE_ANON_KEY=${JSON.stringify(anonKey)}`,
  `SUPABASE_SERVICE_ROLE_KEY=${JSON.stringify(serviceKey)}`,
  'NEXT_PUBLIC_APP_URL="http://localhost:3678"',
  'CAPTUTO_DEV_BACKEND="local"',
  '',
].join('\n'), { mode: 0o600 });

const headers = { apikey: serviceKey, Authorization: `Bearer ${serviceKey}`, 'Content-Type': 'application/json' };
const listed = await fetch(`${apiUrl}/auth/v1/admin/users?page=1&per_page=1000`, { headers });
if (!listed.ok) throw new Error(`Local user lookup failed (${listed.status}).`);
const users = await listed.json();
const email = 'admin@thevibecompany.co';
const user = users.users?.find(candidate => candidate.email === email);
if (!user) {
  const saved = await fetch(`${apiUrl}/auth/v1/admin/users`, {
    method: 'POST', headers,
    body: JSON.stringify({ email, password: 'adminadmin', email_confirm: true }),
  });
  if (!saved.ok) throw new Error(`Local user seed failed (${saved.status}).`);
}
const login = await fetch(`${apiUrl}/auth/v1/token?grant_type=password`, {
  method: 'POST', headers: { apikey: anonKey, 'Content-Type': 'application/json' },
  body: JSON.stringify({ email, password: 'adminadmin' }),
});
if (!login.ok) throw new Error(`Local account sign-in verification failed (${login.status}).`);
console.log(`Local Supabase ready at ${apiUrl}. Local admin account verified. Credentials saved privately in .env.supabase.local.`);
