-- Migration: Add desktop recording columns to sources table
-- These columns store metadata from the desktop recorder app
-- which captures multi-app workflows with native macOS APIs

-- App that was active when the action was captured
ALTER TABLE public.sources ADD COLUMN IF NOT EXISTS app_bundle_id TEXT;
ALTER TABLE public.sources ADD COLUMN IF NOT EXISTS app_name TEXT;

-- Window title of the active app
ALTER TABLE public.sources ADD COLUMN IF NOT EXISTS window_title TEXT;

-- Semantic action type from the desktop step detector
-- Desktop supports more action types than the browser extension
ALTER TABLE public.sources ADD COLUMN IF NOT EXISTS action_type TEXT;

-- Auto-generated caption from the desktop step detector (template-based)
ALTER TABLE public.sources ADD COLUMN IF NOT EXISTS auto_caption TEXT;

-- Groups sources from the same desktop recording session
ALTER TABLE public.sources ADD COLUMN IF NOT EXISTS recording_id TEXT;

-- Update the click_type constraint to allow desktop action types
ALTER TABLE public.sources DROP CONSTRAINT IF EXISTS sources_click_type_check;
ALTER TABLE public.sources ADD CONSTRAINT sources_click_type_check
  CHECK (click_type IN ('click', 'navigation', 'tab_change', 'type', 'keyboard_shortcut', 'app_switch', 'url_navigation', 'menu_selection', 'drag', 'scroll', 'dialog_interaction', 'manual_marker'));

-- Add index on recording_id for querying sources by recording session
CREATE INDEX IF NOT EXISTS idx_sources_recording_id ON public.sources (recording_id) WHERE recording_id IS NOT NULL;

COMMENT ON COLUMN public.sources.app_bundle_id IS 'macOS bundle ID of the app where the action occurred (e.g. com.google.Chrome)';
COMMENT ON COLUMN public.sources.app_name IS 'Display name of the app where the action occurred (e.g. Google Chrome)';
COMMENT ON COLUMN public.sources.window_title IS 'Title of the active window when the action occurred';
COMMENT ON COLUMN public.sources.action_type IS 'Semantic action type from desktop step detector (click, type, shortcut, app_switch, etc.)';
COMMENT ON COLUMN public.sources.auto_caption IS 'Template-based caption auto-generated by the desktop step detector';
COMMENT ON COLUMN public.sources.recording_id IS 'Groups sources from the same desktop recording session';
