import {beforeEach,it,expect,vi} from 'vitest';
vi.mock('@/lib/auth/request',()=>({resolveRequestUser:vi.fn()}));
vi.mock('@/lib/agent/transcription',()=>({transcribeTutorial:vi.fn()}));
import {resolveRequestUser} from '@/lib/auth/request';
import {transcribeTutorial} from '@/lib/agent/transcription';
import {AgentError} from '@/lib/agent/service';
import {POST} from './route';
const request=(body:unknown)=>new Request('http://localhost/api/transcribe',{method:'POST',body:JSON.stringify(body)});
beforeEach(()=>{vi.resetAllMocks();vi.mocked(resolveRequestUser).mockResolvedValue({userId:'owner',supabase:{}} as never);});
it('requires authentication',async()=>{vi.mocked(resolveRequestUser).mockResolvedValue(null);expect((await POST(request({}))).status).toBe(401);});
it('rejects missing or invalid tutorial IDs before calling transcription',async()=>{expect((await POST(request({tutorialId:'bad'}))).status).toBe(400);expect(transcribeTutorial).not.toHaveBeenCalled();});
it('returns timestamped segments',async()=>{const transcript={segments:[{start:0,end:1,transcript:'Cliquez ici'}]};vi.mocked(transcribeTutorial).mockResolvedValue(transcript);expect(await (await POST(request({tutorialId:crypto.randomUUID()}))).json()).toEqual(transcript);});
it('preserves ownership failures',async()=>{vi.mocked(transcribeTutorial).mockRejectedValue(new AgentError('Tutorial not found',404));expect((await POST(request({tutorialId:crypto.randomUUID()}))).status).toBe(404);});
it('reports provider failure without exposing provider credentials',async()=>{vi.mocked(transcribeTutorial).mockRejectedValue(new Error('private provider error'));const r=await POST(request({tutorialId:crypto.randomUUID()}));expect(r.status).toBe(500);expect((await r.json()).error).not.toContain('private provider');});
